### ISSUE TITLE
Cast bar interrupts itself when trying to cast another spell (but spell continues to cast) - With fix

### ISSUE THREAD

**Issue by Zwyk** [shoestare/eCastingBarClassic#2]
When casting a spell and trying to cast another, it sends a "UNIT_SPELLCAST_FAILED" which stops the cast bar. It's not the current spell that failed to cast but the other spell, so it shouldn't stop the cast bar.

I hotfixed this by changing line 234 to :
`elseif(newevent == "UNIT_SPELLCAST_INTERRUPTED" or (newevent == "UNIT_SPELLCAST_FAILED" and spellname ~= barText.spellname)  ) then`

I don't know if it's enough to cover all cases but it works fine as far as I tested.

**Comment by shoestare** [comment]
Thanks so much @Zwyk, I added the hotfix.
